### ISSUE TITLE
Universal links are not properly supported on push notifications

### ISSUE THREAD

**Issue by tfcporciuncula** [customerio/customerio-ios#262]
**SDK version:** 2.0.4

**Environment:** Development or Production

**Are logs available?** 
N/A

**Describe the bug**
When tapping on a push notification with a universal link as the deep link URL, the app opens but then the browser opens right afterwards.

**To Reproduce**
- Send a universal link as a deep link in a push notification
- Tap on the notification
- Observe the app opens and then the browser opens right afterwards

**Expected behavior**
When tapping on a notification with a universal link, the app opens and the browser doesn't. Universal links work great outside of notifications, so my expectation is that they should work in notifications as well so we can use the same URLs everywhere instead of having to use a custom scheme for the deep links we send in notifications.

The current documentation isn't very clear about this, but based on what I see here it seems like our only option might be to use a custom scheme?

![Screen Shot 2023-02-02 at 10 01 28 AM](https://user-images.githubusercontent.com/750114/217283701-eed3cfc2-0963-4b0c-b885-ab61fffae2ec.png)

HTTPS URLs work great on Android, so it would be nice if they work well on iOS as well. And based on what your docs say [here](https://customer.io/docs/sdk/ios/push/#deep-links), it really seems like universal links were supposed to be supported.

**Screenshots**
N/A

**Additional context**
According to [Apple's docs](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html) (referenced by you [here](https://github.com/customerio/customerio-ios/issues/205#issuecomment-1283794187) as well):

>It’s important to understand that if your app uses [openURL:](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl) to open a universal link to your website, the link does not open in your app. In this scenario, iOS recognizes that the call originates from your app and therefore should not be handled as a universal link by your app.

However, it seems that's what the SDK is doing [here](https://github.com/customerio/customerio-ios/blob/43b3e9706b152fe2dead882336a3f416ba400b73/Sources/MessagingPush/MessagingPush%2BAppDelegate.swift#L68):

```swift
if let deepLinkurl = pushContent.deepLink {
    UIApplication.shared.open(url: deepLinkurl)
}
```

Is there anything more sophisticated the SDK could do to make sure universal links will be handled properly (e.g. something like [this](https://stackoverflow.com/questions/46834222/how-can-i-use-universal-links-when-i-call-openurl-inside-my-own-app))? Or anything we can do on our end?

**Comment by levibostian** [comment]
Sorry your experiencing this problem. We do really appreciate you sharing this issue and all the details with us. 

I do not have an answer for you at the moment, but wanted to send you a message that we have seen your issue and we are looking into it more to decide what to do next. 

Have a good one!

**Comment by levibostian** [comment]
Update: I have been able to reproduce this behavior in an iOS app. 

I'll update you with progress on fixing the issue. Thanks again for reporting this to us.

**Comment by levibostian** [comment]
Update: [bug fix](https://github.com/customerio/customerio-ios/pull/265) has been merged. 

`2.0.5` has been deployed to SPM. Cocoapods is deploying as we speak and will be ready in ~30 minutes. 

After installing `2.0.5`, you will need to implement this function in your `AppDelegate` to handle the deep link:

```swift
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        guard let universalLinkUrl = userActivity.webpageURL else {
            return false 
        }
        // Parse `universalLinkUrl` object to perform the action you want in your app. 
        // return true from this function if your app handled the deep link. 
        // return false from this function if your app did not handle the deep link and you prefer the deep link to open the deep link URL in a browser. 
    }
}
```

**Comment by tfcporciuncula** [comment]
We're still experiencing the issue on the new version, and we believe [this](https://github.com/customerio/customerio-ios/pull/265/files#r1104311274) is the culprit.

**Comment by levibostian** [comment]
Thanks for the testing and suggestion. Sorry about that mistake that got unnoticed. 

Update: [PR has been opened](https://github.com/customerio/customerio-ios/pull/268) with a bug fix. We are performing QA on this PR as we speak and then will deploy it shortly after.

**Comment by tfcporciuncula** [comment]
@levibostian any updates on the new fix? This has been a big blocker for our team preventing us from using CIO's SDK and we'd really appreciate a new release with the fix.

**Comment by levibostian** [comment]
Yes, I can provide an update. 

[The PR for the bug fix](https://github.com/customerio/customerio-ios/pull/268) is open and continuing to QA test by our team. 

Although I cannot give an estimate at this time, the task is at the top of our team's priority list. Therefore, I hope to have this fix released as soon as possible.

**Comment by levibostian** [comment]
@tfcporciuncula 2.0.6 has been deployed to production with the bug fix. 

Our official docs [have been updated](https://customer.io/docs/sdk/ios/push/#universal-links-deep-links) to include instructions for this 2.0.6 release. 

Thanks again for reporting this issue to us!

**Comment by alvesmarcos** [comment]
I'm still experiencing this issue in the latest version (2.7.8). When I open the universal link without going through the push notification, it opens normally. However, when I tap on the notification, it not only redirects to my screen correctly but also opens Safari. Do you have any workaround for this situation (@levibostian)? I can also try to record a video to show what is happening, but it's pretty much the same as what is described in the comments above.

**Comment by alvesmarcos** [comment]
I'm providing additional information about this issue.

_UIKitWrapperImpl - Line 34_

```swift
let didHostAppHandleLink = UIApplication.shared.delegate?.application?(UIApplication.shared, continue: openLinkInHostAppActivity, restorationHandler: { _ in }) ?? false
```

The `didHostAppHandleLink` consistently returns false, even when I return true in my `AppDelegate`.

```swift
func application(
    _ application: UIApplication,
    continue userActivity: NSUserActivity,
    restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
) -> Bool {
    return true
}
```

This issue persists despite the fact that the function in `AppDelegate` is set to return true.

**Comment by levibostian** [comment]
To avoid notifying others in this issue to help you, @alvesmarcos, I will respond to you outside of this issue. 

I see you sent us a technical support ticket. I'll respond to you in there.
